apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: qa-backend
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123
  MYSQL_DATABASE: qa_history
  MYSQL_USER: qa_user
  MYSQL_PASSWORD: qa_password123
  DB_USER: qa_user
  DB_PASSWORD: qa_password123
  DB_NAME: qa_history
