apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifact-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=3
  nfs:
    server: qa-storage
    path: /root/url-qa-app/volumes/mlflow-artifacts
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifact-pvc
  namespace: qa-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: mlflow-artifact-pv
