apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: qa-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: mlflow-server
        image: myregistry.com/mlflow-server:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mlflow-server-config
        - secretRef:
            name: mlflow-db-secret
        env:
        - name: MLFLOW_FLASK_SERVER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-auth-secret
              key: flask-secret-key
        - name: MLFLOW_AUTH_CONFIG_PATH
          value: /etc/mlflow/auth_config.ini

        volumeMounts:
        - name: mlflow-artifact-vol
          mountPath: /mlartifacts
        - name: auth-config-vol
          mountPath: /etc/mlflow
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: mlflow-artifact-vol
        persistentVolumeClaim:
          claimName: mlflow-artifact-pvc
      - name: auth-config-vol
        secret:
          secretName: mlflow-auth-secret
          items:
          - key: auth_config.ini
            path: auth_config.ini
